### PR TITLE
fix: drop import of officer defunt functions

### PR DESCRIPTION
**Pull request by davidgohel**
Hello,

This PR remove importation of defunct functions, they are not used in your code so I don't think it will cause any damage:

- slip_in_seqfield
- slip_in_text

KR,
David

### CODE REVIEW

**Comment by john-harrold** [comment]
Hey David. Its been so long that I forgot about these functions. I had to look through my git logs but yeah I stopped using these back in July of 2021. I think I did that because you said they break stuff and would be discontinued in the future. I just forget to remove them from the imports. I assume you want to do this so you can remove them on CRAN. I'll try to submit it to CRAN later today.

**Comment by davidgohel** [comment]
@john-harrold no worry, don't rush for a CRAN deployment for me, I can keep them in officer for now and delete them later :) 

I just ran a rev-dep check without these old functions and found out 'onbrand' imported them but did not use them. As it was easy, I sent you that PR.  

KR
David

**Comment by john-harrold** [comment]
It can take a while for me to find something that will motivate me to update on CRAN. I went ahead and submitted it so you can clear the functions out.

**Comment by john-harrold** [comment]
It's percolating through CRAN now if 1.0.5 doesn't fix it let me know. 

https://cloud.r-project.org/web/checks/check_results_onbrand.html

**Comment by davidgohel** [comment]
thanks, I will suppress officer's defunct functions in the next release :)

**Pull request merged**
